name: Update contributors
on: workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  get-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install @octokit/action
      - run: node .github/actions/get-contributors.cjs
      - run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add src/data/contributors.json
          git commit -m "Update contributors.json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
